package grafica;

import dto.Apartamento;
import java.util.Objects;
import javax.swing.JOptionPane;
import logica.GestorVentas;

/**
 *
 * @author Jonas
 */
public class VentanaInicio extends javax.swing.JFrame {

    /**
     * Creates new form Ventan
     */
    public VentanaInicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btCrearVenta = new javax.swing.JButton();
        btConsulta = new javax.swing.JButton();
        btActualizar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        cjIdentificacion = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inicio");
        getContentPane().setLayout(null);

        btCrearVenta.setBackground(new java.awt.Color(255, 255, 255));
        btCrearVenta.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btCrearVenta.setForeground(new java.awt.Color(0, 0, 0));
        btCrearVenta.setText("Crear venta");
        btCrearVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCrearVentaActionPerformed(evt);
            }
        });
        getContentPane().add(btCrearVenta);
        btCrearVenta.setBounds(180, 30, 210, 50);

        btConsulta.setBackground(new java.awt.Color(255, 255, 255));
        btConsulta.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btConsulta.setForeground(new java.awt.Color(0, 0, 0));
        btConsulta.setText("Consultar venta");
        btConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultaActionPerformed(evt);
            }
        });
        getContentPane().add(btConsulta);
        btConsulta.setBounds(90, 190, 180, 40);

        btActualizar.setBackground(new java.awt.Color(255, 255, 255));
        btActualizar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btActualizar.setForeground(new java.awt.Color(0, 0, 0));
        btActualizar.setText("Actualizar datos y saldo");
        btActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btActualizarActionPerformed(evt);
            }
        });
        getContentPane().add(btActualizar);
        btActualizar.setBounds(290, 190, 250, 40);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 110, 610, 10);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Identificacion: ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(90, 140, 120, 25);

        cjIdentificacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cjIdentificacionKeyTyped(evt);
            }
        });
        getContentPane().add(cjIdentificacion);
        cjIdentificacion.setBounds(230, 140, 310, 24);

        setSize(new java.awt.Dimension(625, 309));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btCrearVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCrearVentaActionPerformed
        new VentanaCrear(this, true).setVisible(true);
    }//GEN-LAST:event_btCrearVentaActionPerformed

    private void btConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultaActionPerformed
        // consultarVenta();
        guardarIdentificacion();
        new VentanaConsultar(this, true).setVisible(true);
    }//GEN-LAST:event_btConsultaActionPerformed

    private void btActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btActualizarActionPerformed
        VentanaInicio.identificacion = Integer.parseInt(cjIdentificacion.getText());
        new VentanaActualizar(this, true).setVisible(true);
    }//GEN-LAST:event_btActualizarActionPerformed

    private void cjIdentificacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cjIdentificacionKeyTyped
        char c = evt.getKeyChar();
        
        if(!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_cjIdentificacionKeyTyped
  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new VentanaInicio().setVisible(true);
            }
        });
    }
    
    public static Integer identificacion;
    
    public void guardarIdentificacion() {
        if (!"".equals(cjIdentificacion.getText())) {
            identificacion = Integer.parseInt(cjIdentificacion.getText());
        } else {
            
            JOptionPane.showMessageDialog(this, "Identificacion vacia.");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btActualizar;
    private javax.swing.JButton btConsulta;
    private javax.swing.JButton btCrearVenta;
    private javax.swing.JTextField cjIdentificacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
