/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package grafica;

import dto.Apartamento;
import java.util.Objects;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import logica.GestorVentas;

/**
 *
 * @author Jonas
 */
public class VentanaConsultar extends javax.swing.JDialog {
    
    DefaultTableModel model;
    /**
     * Creates new form VentanaConsultar
     */
    public VentanaConsultar(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
        consultarVenta();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);
        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 675, 422);

        tabla.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tabla);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(20, 20, 1010, 100);

        setSize(new java.awt.Dimension(1072, 191));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaConsultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaConsultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaConsultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaConsultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VentanaConsultar dialog = new VentanaConsultar(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    public void consultarVenta() {
        
        model = new DefaultTableModel();
        model.addColumn("Nombre");
        model.addColumn("No. piso");
        model.addColumn("No. apartamento");
        model.addColumn("Valor del apartamento");
        model.addColumn("Valor pagado");
        model.addColumn("Saldo restante");
        model.addColumn("Estado de la compra");
        this.tabla.setModel(model);

        GestorVentas gestor = new GestorVentas();
        Apartamento n = new Apartamento();

        for(int i = 0; i < gestor.listaApartamentos.size(); i++){

            n = (Apartamento)gestor.listaApartamentos.get(i);
            if (Objects.equals(n.cliente.obtIdentificacion(), VentanaInicio.identificacion)) {
                break;
            } else {
                n = null;
            }
        }

        if (n == null) {
            JOptionPane.showMessageDialog(this, "No se encontro la identificacion registrada en nuestra base de datos.");
        } else {

            String []info = new String[7];
            info[0] = n.cliente.obtNombre();
            info[1] = Integer.toString(n.num_piso);
            info[2] = Integer.toString(n.num_apartamento);
            info[3] = Integer.toString(n.valor_apartamento);
            info[4] = Integer.toString(n.cliente.obtValor_pagado());
            info[5] = Integer.toString(n.cliente.obtSaldo());
            info[6] = n.estado_compra.name();
            model.addRow(info);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
