package grafica;

import dto.Cliente;
import javax.swing.JOptionPane;
import logica.GestorVentas;

/**
 *
 * @author Jonas
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventan
     */
    public Ventana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cjNombre = new javax.swing.JTextField();
        cjIdentificacion = new javax.swing.JTextField();
        cjPagado = new javax.swing.JTextField();
        cjPiso = new javax.swing.JTextField();
        cjApto = new javax.swing.JTextField();
        btGuardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        jLabel1.setText("VENTA DE APARTAMENTOS");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(200, 30, 340, 30);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("DATOS CLIENTE");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(90, 80, 140, 30);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("DATOS APARTAMENTO");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(450, 80, 210, 25);

        jLabel4.setText("Nombre completo: ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 140, 110, 16);

        jLabel5.setText("Número de identificación: ");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 180, 150, 16);

        jLabel6.setText("Valor pagado: ");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(40, 220, 90, 16);

        jLabel7.setText("Número de piso: ");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(410, 140, 110, 16);

        jLabel8.setText("Número de apto.");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(410, 180, 100, 16);

        cjNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cjNombreActionPerformed(evt);
            }
        });
        getContentPane().add(cjNombre);
        cjNombre.setBounds(200, 140, 140, 24);

        cjIdentificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cjIdentificacionActionPerformed(evt);
            }
        });
        cjIdentificacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cjIdentificacionKeyTyped(evt);
            }
        });
        getContentPane().add(cjIdentificacion);
        cjIdentificacion.setBounds(200, 180, 140, 24);

        cjPagado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cjPagadoActionPerformed(evt);
            }
        });
        cjPagado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cjPagadoKeyTyped(evt);
            }
        });
        getContentPane().add(cjPagado);
        cjPagado.setBounds(200, 220, 140, 24);

        cjPiso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cjPisoActionPerformed(evt);
            }
        });
        cjPiso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cjPisoKeyTyped(evt);
            }
        });
        getContentPane().add(cjPiso);
        cjPiso.setBounds(530, 140, 150, 24);

        cjApto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cjAptoKeyTyped(evt);
            }
        });
        getContentPane().add(cjApto);
        cjApto.setBounds(530, 180, 150, 24);

        btGuardar.setBackground(new java.awt.Color(255, 255, 255));
        btGuardar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btGuardar.setText("GUARDAR");
        btGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGuardarActionPerformed(evt);
            }
        });
        btGuardar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                btGuardarKeyTyped(evt);
            }
        });
        getContentPane().add(btGuardar);
        btGuardar.setBounds(250, 290, 190, 40);

        setSize(new java.awt.Dimension(741, 399));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cjNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cjNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cjNombreActionPerformed

    private void btGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGuardarActionPerformed
        // TODO add your handling code here:
        crearVenta();
    }//GEN-LAST:event_btGuardarActionPerformed

    private void cjPisoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cjPisoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cjPisoActionPerformed

    private void btGuardarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btGuardarKeyTyped

    }//GEN-LAST:event_btGuardarKeyTyped

    private void cjPisoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cjPisoKeyTyped
        char c = evt.getKeyChar();
        
        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_cjPisoKeyTyped

    private void cjAptoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cjAptoKeyTyped
        char c = evt.getKeyChar();
        
        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_cjAptoKeyTyped

    private void cjIdentificacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cjIdentificacionKeyTyped
        char c = evt.getKeyChar();
        
        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_cjIdentificacionKeyTyped

    private void cjPagadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cjPagadoKeyTyped
        char c = evt.getKeyChar();
        
        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_cjPagadoKeyTyped

    private void cjIdentificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cjIdentificacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cjIdentificacionActionPerformed

    private void cjPagadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cjPagadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cjPagadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }
    
    public void crearVenta() {
        
        String nombre = cjNombre.getText();
        int identificacion = Integer.parseInt(cjIdentificacion.getText());
        int valor_pagado = Integer.parseInt(cjPagado.getText());
        int piso = Integer.parseInt(cjPiso.getText());
        int num_apto = Integer.parseInt(cjApto.getText());
        
        GestorVentas venta = new GestorVentas();
        Cliente cl = venta.crearCliente(nombre, identificacion, valor_pagado);
        // venta.crearVenta(cl, piso, num_apto, valor_apto);
        
        JOptionPane.showMessageDialog(this, "Creo la venta -> \nNombre: " + nombre + "\nIdentificacion: " + identificacion + "\nValor pagado: " + valor_pagado);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btGuardar;
    private javax.swing.JTextField cjApto;
    private javax.swing.JTextField cjIdentificacion;
    private javax.swing.JTextField cjNombre;
    private javax.swing.JTextField cjPagado;
    private javax.swing.JTextField cjPiso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
