package grafica;

import dto.Apartamento;
import dto.Cliente;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import logica.GestorVentas;

/**
 *
 * @author Jonas
 */
public class VentanaCrear extends javax.swing.JDialog {

    /**
     * Creates new form VentanaCrearVenta
     */
    public VentanaCrear(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cjNombre = new javax.swing.JTextField();
        cjIdentificacion = new javax.swing.JTextField();
        cjPagado = new javax.swing.JTextField();
        cjPiso = new javax.swing.JTextField();
        cjApto = new javax.swing.JTextField();
        btGuardar = new javax.swing.JButton();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("VENTA DE APARTAMENTOS");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(285, 26, 320, 32);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("DATOS CLIENTE");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(137, 70, 137, 35);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("DATOS APARTAMENTO");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(540, 75, 205, 25);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Nombre completo:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(79, 123, 139, 32);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Numero de identificacion: ");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(79, 174, 159, 20);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Valor pagado: ");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(79, 216, 89, 20);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Numero de piso: ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(499, 129, 105, 20);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Numero de apto.: ");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(499, 174, 111, 20);

        cjNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cjNombreKeyTyped(evt);
            }
        });
        getContentPane().add(cjNombre);
        cjNombre.setBounds(256, 128, 208, 24);

        cjIdentificacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cjIdentificacionKeyTyped(evt);
            }
        });
        getContentPane().add(cjIdentificacion);
        cjIdentificacion.setBounds(256, 173, 208, 24);

        cjPagado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cjPagadoKeyTyped(evt);
            }
        });
        getContentPane().add(cjPagado);
        cjPagado.setBounds(256, 215, 208, 24);

        cjPiso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cjPisoKeyTyped(evt);
            }
        });
        getContentPane().add(cjPiso);
        cjPiso.setBounds(622, 128, 149, 24);

        cjApto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cjAptoKeyTyped(evt);
            }
        });
        getContentPane().add(cjApto);
        cjApto.setBounds(622, 173, 149, 24);

        btGuardar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btGuardar.setForeground(new java.awt.Color(0, 0, 0));
        btGuardar.setText("GUARDAR");
        btGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btGuardar);
        btGuardar.setBounds(328, 314, 232, 46);

        setSize(new java.awt.Dimension(877, 435));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGuardarActionPerformed
        crearVenta();
    }//GEN-LAST:event_btGuardarActionPerformed

    private void cjNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cjNombreKeyTyped

    }//GEN-LAST:event_cjNombreKeyTyped

    private void cjIdentificacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cjIdentificacionKeyTyped
        char c = evt.getKeyChar();
        
        if(!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_cjIdentificacionKeyTyped

    private void cjPagadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cjPagadoKeyTyped
        char c = evt.getKeyChar();
        
        if(!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_cjPagadoKeyTyped

    private void cjPisoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cjPisoKeyTyped
        char c = evt.getKeyChar();
        
        if(!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_cjPisoKeyTyped

    private void cjAptoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cjAptoKeyTyped
        char c = evt.getKeyChar();
        
        if(!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_cjAptoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VentanaCrear dialog = new VentanaCrear(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    public void crearVenta() {
        String nombre = cjNombre.getText();
        int identificacion = Integer.parseInt(cjIdentificacion.getText());
        int valor_pagado = Integer.parseInt(cjPagado.getText());
        int piso = Integer.parseInt(cjPiso.getText());
        int num_apto = Integer.parseInt(cjApto.getText());
        
        GestorVentas venta = new GestorVentas();
        int valor_apto = venta.calcValorApto(piso);
        
        Cliente cl = venta.crearCliente(nombre, identificacion, valor_pagado, valor_apto);
        Apartamento a = venta.crearVenta(cl, piso, num_apto, valor_apto);
        
        JOptionPane.showMessageDialog(this, "Creo la venta -> \n- Nombre: " + nombre + "\n- Identificacion: " + identificacion + "\n- Valor del apto: " + valor_apto + "\n- Saldo: " + cl.obtSaldo());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btGuardar;
    private javax.swing.JTextField cjApto;
    private javax.swing.JTextField cjIdentificacion;
    private javax.swing.JTextField cjNombre;
    private javax.swing.JTextField cjPagado;
    private javax.swing.JTextField cjPiso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    // End of variables declaration//GEN-END:variables
}
