package grafica;

import dto.Apartamento;
import dto.Cliente;
import javax.swing.JOptionPane;
import logica.GestorVentas;
import utilidades.GArchivos;

/**
 *
 * @author Jonas
 */
public class VentanaCrear extends javax.swing.JDialog {

    /**
     * Creates new form VentanaCrearVenta
     */
    public VentanaCrear(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cjNombre = new javax.swing.JTextField();
        cjIdentificacion = new javax.swing.JTextField();
        cjPagado = new javax.swing.JTextField();
        cjPiso = new javax.swing.JTextField();
        cjApto = new javax.swing.JTextField();
        btGuardar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(18, 20, 32));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(245, 249, 233));
        jLabel1.setText("DATOS CLIENTE");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(150, 90, 170, 35);

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(245, 249, 233));
        jLabel3.setText("DATOS APARTAMENTO");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(560, 100, 250, 27);

        jLabel5.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(245, 249, 233));
        jLabel5.setText("Nombre completo");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(30, 140, 150, 32);

        jLabel6.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(245, 249, 233));
        jLabel6.setText("Numero de identificación ");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(30, 190, 194, 21);

        jLabel7.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(245, 249, 233));
        jLabel7.setText("Valor pagado ");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(30, 230, 108, 21);

        jLabel4.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(245, 249, 233));
        jLabel4.setText("Numero de piso ");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(510, 150, 140, 21);

        jLabel8.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(245, 249, 233));
        jLabel8.setText("Numero de apto.");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(510, 190, 150, 21);

        cjNombre.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        cjNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cjNombreKeyTyped(evt);
            }
        });
        jPanel1.add(cjNombre);
        cjNombre.setBounds(230, 150, 208, 20);

        cjIdentificacion.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        cjIdentificacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cjIdentificacionKeyTyped(evt);
            }
        });
        jPanel1.add(cjIdentificacion);
        cjIdentificacion.setBounds(230, 190, 208, 27);

        cjPagado.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        cjPagado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cjPagadoKeyTyped(evt);
            }
        });
        jPanel1.add(cjPagado);
        cjPagado.setBounds(230, 230, 208, 27);

        cjPiso.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        cjPiso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cjPisoKeyTyped(evt);
            }
        });
        jPanel1.add(cjPiso);
        cjPiso.setBounds(670, 150, 149, 27);

        cjApto.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        cjApto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cjAptoKeyTyped(evt);
            }
        });
        jPanel1.add(cjApto);
        cjApto.setBounds(670, 190, 149, 27);

        btGuardar.setBackground(new java.awt.Color(127, 99, 110));
        btGuardar.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        btGuardar.setText("Guardar");
        btGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btGuardar);
        btGuardar.setBounds(330, 300, 232, 46);

        jPanel2.setBackground(new java.awt.Color(127, 99, 110));
        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(245, 249, 233));
        jLabel2.setText("Venta de Apartamentos");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(320, 20, 280, 32);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 870, 70);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(886, 429));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGuardarActionPerformed
        crearVenta();
    }//GEN-LAST:event_btGuardarActionPerformed

    private void cjNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cjNombreKeyTyped

    }//GEN-LAST:event_cjNombreKeyTyped

    private void cjIdentificacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cjIdentificacionKeyTyped
        char c = evt.getKeyChar();
        
        if(!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_cjIdentificacionKeyTyped

    private void cjPagadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cjPagadoKeyTyped
        char c = evt.getKeyChar();
        
        if(!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_cjPagadoKeyTyped

    private void cjPisoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cjPisoKeyTyped
        char c = evt.getKeyChar();
        
        if(!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_cjPisoKeyTyped

    private void cjAptoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cjAptoKeyTyped
        char c = evt.getKeyChar();
        
        if(!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_cjAptoKeyTyped
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                VentanaCrear dialog = new VentanaCrear(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
 
    public void crearVenta() {
        
        String nombre = null;
        Integer identificacion = null;
        Integer valor_pagado = null;
        Integer piso = null;
        Integer num_apto = null;
        Integer valor_apto = null;
        
        GestorVentas venta = new GestorVentas();
        
        if (!"".equals(cjNombre.getText()) && !"".equals(cjIdentificacion.getText()) && !"".equals(cjPagado.getText()) && !"".equals(cjPiso.getText()) && !"".equals(cjApto.getText())) {
            nombre = cjNombre.getText();
            identificacion = Integer.parseInt(cjIdentificacion.getText());
            valor_pagado = Integer.parseInt(cjPagado.getText());
            piso = Integer.parseInt(cjPiso.getText());
            num_apto = Integer.parseInt(cjApto.getText());
            valor_apto = venta.calcValorApto(piso);
        }
        
        Cliente cl = venta.crearCliente(nombre, identificacion, valor_pagado, valor_apto);
        Apartamento apt = venta.crearVenta(cl, piso, num_apto, valor_apto);
        
        if (apt != null) {
            // Si el piso esta en el rango correcto
            if (piso != null && (piso < 1 || piso > 24)) {
                
                JOptionPane.showMessageDialog(this, "El número de piso debe ser entre 1 y 24.");
            } // Si el apartamento esta en el rango correcto
            else if (num_apto != null && (num_apto < 1 || num_apto > 10)) {
                
                JOptionPane.showMessageDialog(this, "El número de apartamento debe ser entre 1 y 10.");
            } // Si la cuota inicial es de minimo 10%
            else if (valor_pagado < (valor_apto * 0.10)) {
                
                JOptionPane.showMessageDialog(this, "La cuota tiene que ser minimo de: " + (valor_apto * 10) / 100 + ".\nQue corresponde al 10% del valor del apartamento, el cual es: " + valor_apto);
            } // Si el apartamento ya ha sido apartado por una persona
            else if (venta.aptoApartado(piso, num_apto)) {
                
                JOptionPane.showMessageDialog(this, "Este apartamento ya ha sido apartado por otra persona.");
            }
            else  {
                
                venta.listaApartamentos.add(apt);
                boolean b = GArchivos.guardar("listaApartamentos.ap", venta.listaApartamentos);
                JOptionPane.showMessageDialog(this, "Se creo la venta exitosamente!");
                dispose();
            }
        } else {
            
            JOptionPane.showMessageDialog(this, "No se creo la venta :(");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btGuardar;
    private javax.swing.JTextField cjApto;
    private javax.swing.JTextField cjIdentificacion;
    private javax.swing.JTextField cjNombre;
    private javax.swing.JTextField cjPagado;
    private javax.swing.JTextField cjPiso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    // End of variables declaration//GEN-END:variables
}
