/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package grafica;

import dto.Apartamento;
import java.util.ArrayList;
import java.util.Objects;
import javax.swing.JOptionPane;
import utilidades.GArchivos;

/**
 *
 * @author Jonas
 */
public class VentanaActualizar extends javax.swing.JDialog {

    /**
     * Creates new form VentanaActualizar
     */
    public VentanaActualizar(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        ponerValores();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cjNombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cjPagado = new javax.swing.JTextField();
        cjPiso = new javax.swing.JTextField();
        cjApto = new javax.swing.JTextField();
        btGuardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("VENTA DE APARTAMENTOS");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(291, 26, 320, 32);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("DATOS CLIENTE");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(137, 70, 137, 35);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Valor pagado: ");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(80, 180, 89, 20);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("DATOS APARTAMENTO");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(546, 75, 205, 25);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Numero de piso: ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(499, 129, 105, 20);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Numero de apto.: ");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(499, 174, 111, 20);

        cjNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cjNombreActionPerformed(evt);
            }
        });
        cjNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cjNombreKeyTyped(evt);
            }
        });
        getContentPane().add(cjNombre);
        cjNombre.setBounds(250, 130, 208, 24);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Nombre completo:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(79, 123, 139, 32);

        cjPagado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cjPagadoKeyTyped(evt);
            }
        });
        getContentPane().add(cjPagado);
        cjPagado.setBounds(250, 170, 208, 24);

        cjPiso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cjPisoKeyTyped(evt);
            }
        });
        getContentPane().add(cjPiso);
        cjPiso.setBounds(622, 128, 149, 24);

        cjApto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cjAptoKeyTyped(evt);
            }
        });
        getContentPane().add(cjApto);
        cjApto.setBounds(622, 173, 149, 24);

        btGuardar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btGuardar.setForeground(new java.awt.Color(0, 0, 0));
        btGuardar.setText("GUARDAR");
        btGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btGuardar);
        btGuardar.setBounds(320, 240, 232, 46);

        setSize(new java.awt.Dimension(883, 351));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cjNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cjNombreKeyTyped

    }//GEN-LAST:event_cjNombreKeyTyped

    private void cjPagadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cjPagadoKeyTyped
        char c = evt.getKeyChar();

        if(!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_cjPagadoKeyTyped

    private void cjPisoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cjPisoKeyTyped
        char c = evt.getKeyChar();

        if(!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_cjPisoKeyTyped

    private void cjAptoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cjAptoKeyTyped
        char c = evt.getKeyChar();

        if(!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_cjAptoKeyTyped

    private void btGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGuardarActionPerformed
        actualizarCambios();
    }//GEN-LAST:event_btGuardarActionPerformed

    private void cjNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cjNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cjNombreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VentanaActualizar dialog = new VentanaActualizar(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    public ArrayList apartamentos = (ArrayList)GArchivos.leer("listaApartamentos.ap");
    public int posicion;
    
    public void ponerValores() {
        Apartamento n = new Apartamento();

        for(int i = 0; i < apartamentos.size(); i++){

            n = (Apartamento)apartamentos.get(i);
            if (Objects.equals(VentanaInicio.identificacion, n.cliente.obtIdentificacion())) {
                posicion = i;
                cjNombre.setText(n.cliente.obtNombre());
                cjPagado.setText(n.cliente.obtValor_pagado().toString());
                cjPiso.setText(n.num_piso.toString());
                cjApto.setText(n.num_apartamento.toString());
            }
        }
    }
        
    public void actualizarCambios() {
        Apartamento n = (Apartamento)apartamentos.get(posicion);
        
        n.cliente.modiNombre(cjNombre.getText());
        n.cliente.modiValor_pagado(Integer.parseInt(cjPagado.getText()));
        n.num_piso = Integer.parseInt(cjPiso.getText());
        n.num_apartamento = Integer.parseInt(cjApto.getText());
        
        apartamentos.set(posicion, n);
        boolean b = GArchivos.guardar("listaApartamentos.ap", apartamentos);
        JOptionPane.showMessageDialog(this, "Se guardo (Teoricamente)" + b);
        dispose();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btGuardar;
    private javax.swing.JTextField cjApto;
    private javax.swing.JTextField cjNombre;
    private javax.swing.JTextField cjPagado;
    private javax.swing.JTextField cjPiso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
